version: '2'
services:
  tink:
    build: .
    # command: lein run
    environment:
      DATABASE_URL: "postgresql://postgres:secret@psql:5432/tink"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - psql
      - kafka
      - zookeeper

  psql:
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "tink"

  zookeeper:
    image: zookeeper:latest
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: ches/kafka:latest
    ports:
      - "9092:9092"
      - "7203:7203"
    volumes:
      - ./tmp/kafka-data:/data
      - ./tmp/kafka-logs:/logs
    links:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"
