version: 2

jobs:
  build:
    working_directory: ~/tink
    docker:
      - image: python:3.5
        environment:
          DATABASE_URL: "postgresql://postgres:secret@psql:5432/tink"
      - image: postgres:9.6
        environment:
          POSTGRES_PASSWORD: "secret"
          POSTGRES_DB: "tink"
      - image: zookeeper:latest
      - image: ches/kafka:latest
        environment:
          ZOOKEEPER_CONNECTION_STRING: "zookeeper:2181"

    steps:
      - checkout
      - restore_cache:
          key: tink-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - run:
          command: |
            apt-get update
            apt-get --assume-yes install apt-utils
            apt-get --assume-yes upgrade
            apt-get --assume-yes install libpq-dev libsnappy-dev
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-test.txt
      - save_cache:
          key: tink-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            nosetests

